### ISSUE TITLE
Ability to provide 'master' and 'zk_hosts' parameters as environment variables.

### ISSUE THREAD

**Issue by brandongalbraith** [kadel/Dockerfiles#5]
Hey @kadel!

What are your thoughts on exposing 'master' and 'zk_hosts' to the container as environment variables instead of command line arguments when starting the container? I wasn't sure if there was a specific reason for using command line args instead of env vars, and env vars are much cleaner for passing settings into a container.

**Comment by kadel** [comment]
Hi @brandongalbraith 
In this case I chose just passing arguments to chronos binary, because it is much simpler and you can run docker container with same arguments as chronos binary.

We can add ability to configure `master` and `zk_hosts` through env vars but also keeping possibility to configure it via args.

**Comment by brandongalbraith** [comment]
:+1:

**Comment by kadel** [comment]
Sorry,  but I'm not using zookeper anymore :-(
